// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYA4jFkrklYBrzkrByvYbZatz2wuL5zf0',
    appId: '1:458365143660:web:99a2cdc6830876f96be649',
    messagingSenderId: '458365143660',
    projectId: 'hazimete-calendar',
    authDomain: 'hazimete-calendar.firebaseapp.com',
    storageBucket: 'hazimete-calendar.appspot.com',
    measurementId: 'G-Y8V4DBEW02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXGIUgtz5pERObtaE9plazUfb0elCRoFI',
    appId: '1:458365143660:android:ed7905616f3539f36be649',
    messagingSenderId: '458365143660',
    projectId: 'hazimete-calendar',
    storageBucket: 'hazimete-calendar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwhWVqeD8Of7VKhg5XI56NAAZADzMi98w',
    appId: '1:458365143660:ios:11cf27e1c0c7fe306be649',
    messagingSenderId: '458365143660',
    projectId: 'hazimete-calendar',
    storageBucket: 'hazimete-calendar.appspot.com',
    iosBundleId: 'com.google.firebase.presents.hazimetecalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwhWVqeD8Of7VKhg5XI56NAAZADzMi98w',
    appId: '1:458365143660:ios:c4843024d030416f6be649',
    messagingSenderId: '458365143660',
    projectId: 'hazimete-calendar',
    storageBucket: 'hazimete-calendar.appspot.com',
    iosBundleId: 'com.google.firebase.presents.hazimetecalendar.RunnerTests',
  );
}
